### PR TITLE
Migrate to for_each. Get rid of *_num options (breaking change). Fix destructiveness of updates. Add new playground test suite for testing updates.

### LINKED ISSUE #11: Adding new bindings is a destructive operation
Version 1.0.0

When used with `mode = "authoritative"`, when adding a new binding the module will sometimes attempt to delete one or more of the existing bindings. It then attempts to re-create them. The deletion events occur before any of the creation events and the delay between deletion and creation of bindings can be on the order of minutes.

This is problematic when used on production systems. The time between bindings being deleted and re-created is long enough that live workloads could experience IAM permission errors.

Ideally, adding new bindings would be a purely additive operation. Alternatively, if the delay between deletion and creation of bindings could be constrained to seconds instead of minutes, the risk to production systems would be minimized.

### LINKED ISSUE #38: Fix adding new bindings in additive mode
Hi,

It seems that when you add a new project binding in additive mode, the module destroys everything and recreates all bindings from scratch. It would be better if the module adds only new binding to the Terraform state.

### Envinronemt

```
Terraform v0.12.4
+ provider.external v1.2.0
+ provider.google v2.10.0
+ provider.google-beta v2.10.0
```

### Current behaviour

Firstly, I have the following Terraform code:

```
module "bindings" {
  source   = "terraform-google-modules/iam/google"
  version  = "2.0.0"
  projects = [var.project]

  mode = "additive"

  bindings = {
    "roles/bigquery.dataViewer" = [
      "serviceAccount:service-account-0@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-1@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-2@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-3@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-4@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-5@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-6@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-7@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-8@${var.project}.iam.gserviceaccount.com",
    ]
  }
}
```

When I apply the changes and call `terraform state list` I can see the following list:

```
module.bindings.data.external.additive_bindings_temp_struct
module.bindings.google_project_iam_member.project_iam_additive[0]
module.bindings.google_project_iam_member.project_iam_additive[1]
module.bindings.google_project_iam_member.project_iam_additive[2]
module.bindings.google_project_iam_member.project_iam_additive[3]
module.bindings.google_project_iam_member.project_iam_additive[4]
module.bindings.google_project_iam_member.project_iam_additive[5]
module.bindings.google_project_iam_member.project_iam_additive[6]
module.bindings.google_project_iam_member.project_iam_additive[7]
module.bindings.google_project_iam_member.project_iam_additive[8]
```

Then, when I want to add a service account (as you can see, only *serviceAccount:service-account-9@${var.project}.iam.gserviceaccount.com* is added) to existing binding:

```
module "bindings" {
  source   = "terraform-google-modules/iam/google"
  version  = "2.0.0"
  projects = [var.project]

  mode = "additive"

  bindings = {
    "roles/bigquery.dataViewer" = [
      "serviceAccount:service-account-0@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-1@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-2@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-3@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-4@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-5@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-6@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-7@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-8@${var.project}.iam.gserviceaccount.com",
      "serviceAccount:service-account-9@${var.project}.iam.gserviceaccount.com",
    ]
  }
}
```

and call `terraform plan` I get the following output:

```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.bindings.data.external.additive_bindings_temp_struct: Refreshing state...
module.bindings.google_project_iam_member.project_iam_additive[2]: Refreshing state... [id=<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-6@<my-gcp-project>.iam.gserviceaccount.com]
module.bindings.google_project_iam_member.project_iam_additive[0]: Refreshing state... [id=<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-8@<my-gcp-project>.iam.gserviceaccount.com]
module.bindings.google_project_iam_member.project_iam_additive[6]: Refreshing state... [id=<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-2@<my-gcp-project>.iam.gserviceaccount.com]
module.bindings.google_project_iam_member.project_iam_additive[4]: Refreshing state... [id=<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-4@<my-gcp-project>.iam.gserviceaccount.com]
module.bindings.google_project_iam_member.project_iam_additive[1]: Refreshing state... [id=<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-7@<my-gcp-project>.iam.gserviceaccount.com]
module.bindings.google_project_iam_member.project_iam_additive[7]: Refreshing state... [id=<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-1@<my-gcp-project>.iam.gserviceaccount.com]
module.bindings.google_project_iam_member.project_iam_additive[3]: Refreshing state... [id=<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-5@<my-gcp-project>.iam.gserviceaccount.com]
module.bindings.google_project_iam_member.project_iam_additive[5]: Refreshing state... [id=<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-3@<my-gcp-project>.iam.gserviceaccount.com]
module.bindings.google_project_iam_member.project_iam_additive[8]: Refreshing state... [id=<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-0@<my-gcp-project>.iam.gserviceaccount.com]

------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # module.bindings.google_project_iam_member.project_iam_additive[0] must be replaced
-/+ resource "google_project_iam_member" "project_iam_additive" {
      ~ etag    = "GfHM97ODu3h=" -> (known after apply)
      ~ id      = "<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-8@<my-gcp-project>.iam.gserviceaccount.com" -> (known after apply)
      ~ member  = "serviceAccount:service-account-8@<my-gcp-project>.iam.gserviceaccount.com" -> "serviceAccount:service-account-9@<my-gcp-project>.iam.gserviceaccount.com" # forces replacement
        project = "<my-gcp-project>"
        role    = "roles/bigquery.dataViewer"
    }

  # module.bindings.google_project_iam_member.project_iam_additive[1] must be replaced
-/+ resource "google_project_iam_member" "project_iam_additive" {
      ~ etag    = "GfHM97ODu3h=" -> (known after apply)
      ~ id      = "<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-7@<my-gcp-project>.iam.gserviceaccount.com" -> (known after apply)
      ~ member  = "serviceAccount:service-account-7@<my-gcp-project>.iam.gserviceaccount.com" -> "serviceAccount:service-account-8@<my-gcp-project>.iam.gserviceaccount.com" # forces replacement
        project = "<my-gcp-project>"
        role    = "roles/bigquery.dataViewer"
    }

  # module.bindings.google_project_iam_member.project_iam_additive[2] must be replaced
-/+ resource "google_project_iam_member" "project_iam_additive" {
      ~ etag    = "GfHM97ODu3h=" -> (known after apply)
      ~ id      = "<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-6@<my-gcp-project>.iam.gserviceaccount.com" -> (known after apply)
      ~ member  = "serviceAccount:service-account-6@<my-gcp-project>.iam.gserviceaccount.com" -> "serviceAccount:service-account-7@<my-gcp-project>.iam.gserviceaccount.com" # forces replacement
        project = "<my-gcp-project>"
        role    = "roles/bigquery.dataViewer"
    }

  # module.bindings.google_project_iam_member.project_iam_additive[3] must be replaced
-/+ resource "google_project_iam_member" "project_iam_additive" {
      ~ etag    = "GfHM97ODu3h=" -> (known after apply)
      ~ id      = "<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-5@<my-gcp-project>.iam.gserviceaccount.com" -> (known after apply)
      ~ member  = "serviceAccount:service-account-5@<my-gcp-project>.iam.gserviceaccount.com" -> "serviceAccount:service-account-6@<my-gcp-project>.iam.gserviceaccount.com" # forces replacement
        project = "<my-gcp-project>"
        role    = "roles/bigquery.dataViewer"
    }

  # module.bindings.google_project_iam_member.project_iam_additive[4] must be replaced
-/+ resource "google_project_iam_member" "project_iam_additive" {
      ~ etag    = "GfHM97ODu3h=" -> (known after apply)
      ~ id      = "<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-4@<my-gcp-project>.iam.gserviceaccount.com" -> (known after apply)
      ~ member  = "serviceAccount:service-account-4@<my-gcp-project>.iam.gserviceaccount.com" -> "serviceAccount:service-account-5@<my-gcp-project>.iam.gserviceaccount.com" # forces replacement
        project = "<my-gcp-project>"
        role    = "roles/bigquery.dataViewer"
    }

  # module.bindings.google_project_iam_member.project_iam_additive[5] must be replaced
-/+ resource "google_project_iam_member" "project_iam_additive" {
      ~ etag    = "GfHM97ODu3h=" -> (known after apply)
      ~ id      = "<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-3@<my-gcp-project>.iam.gserviceaccount.com" -> (known after apply)
      ~ member  = "serviceAccount:service-account-3@<my-gcp-project>.iam.gserviceaccount.com" -> "serviceAccount:service-account-4@<my-gcp-project>.iam.gserviceaccount.com" # forces replacement
        project = "<my-gcp-project>"
        role    = "roles/bigquery.dataViewer"
    }

  # module.bindings.google_project_iam_member.project_iam_additive[6] must be replaced
-/+ resource "google_project_iam_member" "project_iam_additive" {
      ~ etag    = "GfHM97ODu3h=" -> (known after apply)
      ~ id      = "<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-2@<my-gcp-project>.iam.gserviceaccount.com" -> (known after apply)
      ~ member  = "serviceAccount:service-account-2@<my-gcp-project>.iam.gserviceaccount.com" -> "serviceAccount:service-account-3@<my-gcp-project>.iam.gserviceaccount.com" # forces replacement
        project = "<my-gcp-project>"
        role    = "roles/bigquery.dataViewer"
    }

  # module.bindings.google_project_iam_member.project_iam_additive[7] must be replaced
-/+ resource "google_project_iam_member" "project_iam_additive" {
      ~ etag    = "GfHM97ODu3h=" -> (known after apply)
      ~ id      = "<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-1@<my-gcp-project>.iam.gserviceaccount.com" -> (known after apply)
      ~ member  = "serviceAccount:service-account-1@<my-gcp-project>.iam.gserviceaccount.com" -> "serviceAccount:service-account-2@<my-gcp-project>.iam.gserviceaccount.com" # forces replacement
        project = "<my-gcp-project>"
        role    = "roles/bigquery.dataViewer"
    }

  # module.bindings.google_project_iam_member.project_iam_additive[8] must be replaced
-/+ resource "google_project_iam_member" "project_iam_additive" {
      ~ etag    = "GfHM97ODu3h=" -> (known after apply)
      ~ id      = "<my-gcp-project>/roles/bigquery.dataViewer/serviceaccount:service-account-0@<my-gcp-project>.iam.gserviceaccount.com" -> (known after apply)
      ~ member  = "serviceAccount:service-account-0@<my-gcp-project>.iam.gserviceaccount.com" -> "serviceAccount:service-account-1@<my-gcp-project>.iam.gserviceaccount.com" # forces replacement
        project = "<my-gcp-project>"
        role    = "roles/bigquery.dataViewer"
    }

  # module.bindings.google_project_iam_member.project_iam_additive[9] will be created
  + resource "google_project_iam_member" "project_iam_additive" {
      + etag    = (known after apply)
      + id      = (known after apply)
      + member  = "serviceAccount:service-account-0@<my-gcp-project>.iam.gserviceaccount.com"
      + project = "<my-gcp-project>"
      + role    = "roles/bigquery.dataViewer"
    }

Plan: 10 to add, 0 to change, 9 to destroy.

------------------------------------------------------------------------

This plan was saved to: terraform.plan

To perform exactly these actions, run the following command to apply:
    terraform apply "terraform.plan"
```

### Expected behaviour

It would be better, if Terraform will create a new binding. In this case for role *roles/bigquery.dataViewer* assign a member `serviceAccount:service-account-9@<my-gcp-project>.iam.gserviceaccount.com`:

```
# module.bindings.google_project_iam_member.project_iam_additive[9] will be created
+ resource "google_project_iam_member" "project_iam_additive" {
    + etag    = (known after apply)
    + id      = (known after apply)
    + member  = "serviceAccount:service-account-9@<my-gcp-project>.iam.gserviceaccount.com"
    + project = "<my-gcp-project>"
    + role    = "roles/bigquery.dataViewer"
  }
```

### LINKED ISSUE #46: for_each rewrite
Hi,

It is still a work in progress, but I have started re-writing this module with _for_each_ to work around the count limitations and avoid bindings re-creation when the input map changes:
https://github.com/sleterrier/terraform-google-iam

I don't think the Issues board  is the best place for this, but I thought you might be interested in seeing this new >=0.12.6 approach.

### LINKED ISSUE #69: specifying a single project in projects-iam causes module to do nothing
There is both a project and a projects variable available in the module.  The implication from the docs is that one or the other must be provided.  If you use the former, the module does no work.  It only functions if you specify a list of one project in the projects variable.

### PR DESCRIPTION
**Pull request by cray0000**
- fix #11 
- fix #46 
- fix #38 
- fix #69 

- [x] Add a new test suite to use as a playground to test how the module behaves on role updates
- [x] Figure out a way to stabilize the roles/members order. This lead to breaking changes to the API. More on this below.
- [x] Migrate from `count` to `for_each` for static and dynamic usecases. Remove  `*_num` options
- [x] Add configuration update test into the CI. More on this below.
- [x] Add an upgrade guide from 3.0 to 4.0

## API changes

1. `*_num` options are removed.
2. Support dynamic entities (for example, projects in `projects_iam`) only when 1 entity is passed. If you pass 2 or more, the configuration has to be static, meaning that it can't use any of the other resource's fields to get the entity name from (this includes getting the randomly generated hashes through the `random_id` resource).
3. The roles can never be dynamic.
4. Members can only be dynamic in `authoritative` mode.

## Testing configuration update.

In the `update` test suite I've setup an additional variable `roles` (defaults to `2`) which you can pass as `TF_VAR_roles=3` when running the `converge` command. The fixtures currently support the amount of roles from `1` to `3`. But it's trivial to add more, if needed in future.

This way we can reconverge the `update` test suite with different `TF_VAR_roles` values and verify. And by doing this multiple times we are basically testing the module configuration update behavior.

### CODE REVIEW

**Comment by cray0000** [comment]
Found a way to replicate this with the simplest usecase.
Added a testsuite as a playground to try to fix it.

In the base scenario of having 2 projects and 1 role specified with 1 member in authoritative mode. Adding just one additional role will lead to recreation of one iam resource instead of just reusing it.

https://gist.github.com/cray0000/1f75fec0a6d32d2f31f8a4502e2558cd

File: test/integration/additive/controls/additive.rb [hunk 1]
```diff
@@ -12,6 +12,10 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+# TODO: Get pure integer number from attributes (bug in InSpec).
```
Comment (aaron-lane) [inline test/integration/additive/controls/additive.rb]: Likewise about TODO comments.

File: test/integration/additive/controls/additive.rb [hunk 2]
```diff
@@ -45,14 +49,11 @@
...
 
-  describe folder_bindings(folders[0]) do
-    it { should include role: folder_roles[0], members: member_groups[0] }
-    it { should include role: folder_roles[1], members: member_groups[1] }
-  end
-
-  describe folder_bindings(folders[1]) do
-    it { should include role: folder_roles[0], members: member_groups[0] }
-    it { should include role: folder_roles[1], members: member_groups[1] }
+  for folder in folders do
```
Comment (aaron-lane) [inline test/integration/additive/controls/additive.rb]: Let's try to avoid dynamically defining test cases.

```ruby
describe "folder bindings" do
  it "include the first binding" do
    if roles < 1
      skip "less than 1 roles specified"
    else
      expect(folders).to all include role: folder_roles[0], members: member_groups[0]
    end
  end

  it "include the second binding" do
    if roles < 2
      skip "less than 2 roles specified"
    else
      expect(folders).to all include role: folder_roles[1], members: member_groups[1]
    end
  end
end
```

**Comment by Lirt** [comment]
Hey @cray0000 can I help you with review or testing? 
I have mutliple examples with the issue https://github.com/terraform-google-modules/terraform-google-iam/issues/11, so if you need testing on production, I can do it.

File: modules/helper/main.tf [hunk 3]
```diff
@@ -40,15 +47,57 @@ locals {
...
+    : [
+      for role, members in var.bindings
+      : [
+        for member in members
+        : "${alias}--${role}--${member}"
+      ]
+    ]
+  ]))
+
+  # TODO: Refactor this to force the order somehow.
```
[the remark this answers is not in the document]
Comment (cray0000) [reply modules/helper/main.tf]: Made an issue for this TODO: #66 
And I removed other TODOs, which were related to InSpec `integer` issue, since it requires an upstream change.

File: test/integration/additive/controls/additive.rb (hunk 2 above)
Comment (cray0000) [reply test/integration/additive/controls/additive.rb]: Wow! That's an awesome way to restructure the tests, thanks! Changed all suites to use `all` and an explicit `skip`.

File: docs/upgrading_to_iam_4.0.md [hunk 4]
```diff
@@ -0,0 +1,130 @@
...
+The 3.0 release have added support for applying bindings to dynamic variable values. This functionality was relying on `count` which
+in the end turned out to result in inconsistent module behavior
+when doing the configuration updates.
+
+Here is an example of such *dynamic* configuration in 3.0
+which applies bindings to two projects.
+
+```hcl
+module "project_factory" {
+  count = 2
```
Comment (aaron-lane) [inline docs/upgrading_to_iam_4.0.md]: Modules do not yet support `count`. :smile: These examples should be adjusted to be realistic.

File: docs/upgrading_to_iam_4.0.md [hunk 5]
```diff
@@ -0,0 +1,130 @@
...
+       "serviceAccount:${module.project_factory.service_account_email}",
+     ]
+   }
+-  projects_bindings_num = 1
+ }
++
++module "iam" {
++  source  = "terraform-google-modules/iam/google"
++  version = "~> 4.0"
++
```
Comment (aaron-lane) [inline docs/upgrading_to_iam_4.0.md]:
```suggestion
+
+  mode = "authoritative"
+
```

File: test/integration/static-and-dynamic/controls/static-and-dynamic.rb [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+
+# Member groupings
+member_groups = [
+  attribute('member_group_0'),
+  attribute('member_group_1')
+]
+
+# Projects
+
+for projects in project_groups do
```
Comment (aaron-lane) [inline test/integration/static-and-dynamic/controls/static-and-dynamic.rb]: Again, we should avoid dynamically defining tests. It is acceptable to have repeated code in tests, and we can look at how to refactor it with a library if it becomes difficult to maintain.

File: docs/upgrading_to_iam_4.0.md (hunk 5 above)
Comment (cray0000) [reply docs/upgrading_to_iam_4.0.md]: Great catch! Fixed, thanks

**Comment by morgante** [comment]
@cray0000 Can you make sure tests pass?

File: test/integration/helper/libraries/bindings.rb [hunk 7]
```diff
@@ -67,6 +67,12 @@ class BucketBindings < Bindings
   def get_command(bucket, project)
     "gsutil iam get gs://#{bucket} --project='#{project}' --format='json(bindings)'"
   end
+
+  def get_bindings(command)
+    puts "DEBUG: Bindings output"
```
[the remark this answers is not in the document]
Comment (cray0000) [reply test/integration/helper/libraries/bindings.rb]: oh, good catch, that particular piece managed to slip through. Removed it
